### ISSUE TITLE
Rigidbody2D rotation issues

### ISSUE THREAD

**Issue by juanitogan** [Polarith/AI#23]
I tried your support form late Saturday night and have had no response yet, so I'll try here.

As soon as I attach a target game object in seek or follow or pursue (or anywhere it seems), that target object starts glitching.  Disable the seek component, or remove the game object from the target list, and the target object behaves fine.  Thus, it is pretty clearly Polarith related.  The weirdest part is that I haven't put any AIM components on the target object yet, and yet, AIM is somehow messing with it.

Anyhow, after a ton of testing and digging, I noticed that the rotation value on the target Rigidbody2D is being reset somehow to stay in the -180 to 180 range.  It normally rotates to 360 and beyond.  This resetting may not be a problem with singular objects but this reset really messes with the transformations of objects joined with 2D joints to that object.  For example, in my game, [GRITS Racing](http://gritsracing.com), I have cars with breakable wheels.  Thus, the wheels cannot be children to the body transform.  Thus, when Polarith rotates the RB of the car body 360 degrees to stay in bounds, it whacks out the wheels.  Something else is also messing with driving straight, but I haven't figure that one out yet... but I bet it's something similar with Polarith.

I still have enough control to keep building up the AI but I can't publish anything with Polarith until this is fixed.

**Comment by juanitogan** [comment]
Oh, yeah: Unity 2017.4.23f1 (the latest LTS version) on Windows 10 64-bit, and Polarith 1.6 (tried both free and pro).

**Comment by MartinWieczorek** [comment]
Hey Matt,
Unfortunately, it seems that your message didn´t appear in our support system. But here is also a good place for questions.
I read your problem description, and for now, it´s quite hard to understand and reproduce it. So it would help us understand your problem better if you could send us a video or an example package where we can observe this problem more clearly.
Please send it to support@polarith.com, and we will look at it.

**Comment by juanitogan** [comment]
Good to know it was a technical glitch or ebcak and that I wasn't being ignored on purpose. 😁 

I've sent an example project showing the issue.  You're right, it was much harder to reproduce than I anticipated.  It took me hours to narrow it down to a simple example based on one of your Lab2D examples.

It turns out the Seek and other similar components were red herrings.  Yes, turning Seek on and off makes the problem come and go.  But, the real issue seems to be with the Steering Filter component and mixing Filtered Environments on some components with Game Object lists on other components.  The target object must also have a Rigidbody2D **and** a 2D collider.  Even weirder, the 2D collider can be disabled but it must still be there to see the issue.

Regarding the Steering Filter on the seeker object, it doesn't seem to matter if it is wired up correctly or not.  Simply adding it to the seeker object will cause the issue to appear in the target object.  That is, if the target object is specified by Game Object list instead of Filtered Environment.  **Thus, the workaround seems to be to ALWAYS use Filtered Environments on ALL components when using the Steering Filter.**

I had neglected to use Filtered Environments everywhere because I have one case where only one agent will ever pursue one player (while avoid environment walls and such).  Thus, it was easier to skip the extra environment setup for this case.  And the Perception Pipeline notes didn't seem to indicate that an environment in this case would improve performance.  So, I skipped it.  Oops.  I believe this is a bug but, if not, there should me more warnings against it.

Happy to have found the workaround, though. 🎉

For others reading this, the odd behavior can be seen in the rotation value here:

![Polarith01a](https://user-images.githubusercontent.com/2923222/55202837-bb3c2e00-518e-11e9-9c48-7e783cfbfc3d.png)

When, instead, the rotation value should not be limited, like seen here:

![Polarith02a](https://user-images.githubusercontent.com/2923222/55202840-bf684b80-518e-11e9-9dce-e7c61899bccd.png)

**Comment by mzettwitz** [comment]
Hi Matt,

At first, we are glad, that you found a workaround by yourself. You are right, it seems to be a bug. I've got an educated guess what causes it: while perceiving the GameObjects, we compute the information of the bounds (based on the collider!), too. Since Unity won't give us the data of an oriented bounding box (thanks by the way), we need to rotate the object to get the data. Something might be broken at this point. Things get even stranger: we use the same [method](http://docs.polarith.com/ai/class_polarith_1_1_a_i_1_1_move_1_1_steering_percept_a93ad183bda09903d1c1639c32eee5c92.html#a93ad183bda09903d1c1639c32eee5c92) to receive the bounds information in the perception pipeline using environments as well as for directly assigned GameObjects.
We will find a solution. This behaviour is absolutely not intended.

Have a freaky Friday,
Martin 'Zetti' Zettwitz from Polarith

**Comment by juanitogan** [comment]
Yeah, that it is a very strange conundrum that I had wondered about.  Why one way and not the other?  Very curious.  Anyway...

I forgot to mention yesterday that I only isolated the rotational issue (which is a modular math thing).  I didn't bother trying to isolate the linear issue because I have fewer clues to go on there.  My hope is that when you find one, you will find the other -- either in the same code, or in similar code.

I did realize this morning that I do have some other clues on the linear thing, so I went back and did some more testing under glitch conditions.  If I can get the car to a high enough speed in spite of the glitch (which slows the car down) it will draw small skids at each glitch.  Thus, I was eventually noticing a long-short-long-short pattern between these skids.  It occurred to me this might be due to the AIM Context running at 20 FPS and the physics running at 50 FPS.  Skids like this:

![PolarithContext20FPS](https://user-images.githubusercontent.com/2923222/55257106-85e21f80-5224-11e9-8c12-a42082b65452.png)

So, I switched the Context to 25 FPS (something I was planning to do anyhow).  This slows the car down even more (so it was harder to get a good screen shot of the skids) but where I could get three skids in a row, they were regularly spaced at the closer spacing.

What this shows is that something is being rewritten on the target object every Context frame (and not just when rotation passes 180).  According to freeze frames, the wheels leap ahead of the car on occasion.  Thus, I'm assuming the rigidbody's position gets reset every Context frame, causing it to drag.

Hope this extra info helps.

Thanks for the Freaky Friday!
Matt

**Comment by mzettwitz** [comment]
Thanks for the additional input. Do these skids occur when you use the environment instead of GameObjects, too? 

Have a great start into the week.
Martin 'Zetti' Zettwitz from Polarith

**Comment by juanitogan** [comment]
Sorry, I could have been more clear about what "glitch conditions" were.  I have no issues (no skids, no nothing) when using Game Objects lists on Environments.  Only when using Game Objects lists on behavior components as previously described.  I had gone backwards and did some more testing out of curiosity.

I suspect that you'll find that whatever is causing the linear problem is also causing the rotation problem.  I don't see a rotational problem every Context frame -- not until the modular math kicks in -- but it's probably there.  Curiously, the Transform always displays the modular rotation value on Z, so it's as if the Transform values are being written back to the RigidBody2D, but after physics solving, so it messes with everything.  But that's just a wild guess.

**Comment by juanitogan** [comment]
Unfortunately, I just found a limitation to the Environment workaround.  When I add an object that already has a high or low rotation value to the Game Objects list on an Environment during game play, that target object gets rotated back to within -180 to 180 as soon as I add it.  This kills a critical part of the AI design.

**Comment by mzettwitz** [comment]
Hay Matt, there might be two workarounds. Currently, you add GameObjects to the environment list. Maybe it will work if you use Unity layers instead. Regardless, I would recommend that you do it this way for convenience. Note, that you still need to update the environment if you add something on runtime. 
My second approach would pre-cache the GameObjects, if this is an option for you. So you would add all GameObjects in advance and activate them during runtime.

Have a thirsty Thursday,
Martin 'Zetti' Zettwitz from Polarith.

**Comment by juanitogan** [comment]
Thanks, but I can't use the layers option.  I tested with layers early on out of convenience, but I abandoned using Polarith with them after initial testing because they are too important to mess with due to their primary purpose in physics games: setting up collision layers.  I thought long and hard about how to use them for both collision layers and interest layers but it became apparent that it would quickly become much more complex than it is worth.  Don't mess with the collision layers if you use them as such.  Tags might work but, no, I'm happy with running a loop to sort the various objects into their proper environments.

Also, I sincerely doubt using layers would solve the issue given that it is the changing of the environment during runtime that breaks things and not how the environment is loaded.

Caching won't work either since instantiation is not the issue.  These are not always new objects I am assigning to an environment during play.  The primary interest of an agent can switch from one player to another during game play -- and even from player to another agent, and so forth.  Thus, the only workaround I've thought of so far is to try putting each player and each agent into their own environment and switching environments and/or behavior components instead of simply changing the gameobjects list.  But this would be a major pain to set up and test out of blind hope.  Or, maybe, you have another way of handling this common use case that I haven't figured out yet.

Given how much I've narrowed down the bug for you, I would think there can't be too many places to look for it.  With this latest info, it appears that items not in an environment are being treated like a new item of interest every context frame -- the same as an item that was just added to an environment during play.  Furthermore, when an item of interest is destroyed, similar rotation adjustments happen to other items in play, but I haven't identified the exact reason there yet to explain it properly.  Regardless, I'm sure it will go away when you fix the primary issue here.

**Comment by mzettwitz** [comment]
Hi Matt, 
Good news: I found the issue (at least for the rotational bug). Bad news: I can't fix it right away since Unity makes some problems. 
For your interest: the problem is caused by the Unity Transform. Since Unity gives us only the axis-aligned bounds, we need to rotate the perceived object to Quaternion.Identity, get its extends and rotate it back. Regardless I save the rotation in Euler angles or Quaternion, Unity will clamp it within the 360 degrees ratio which effects the Rigidbody as well. It works well if you rotate the object using force (which may be with you), but causes the problems as we see if you rotate using the Transform.

Have a great day,
Martin 'Zetti' Zettwitz from Polarith.

**Comment by juanitogan** [comment]
Thanks for sending the hotfix.  It appears to have fixed all issues reported here: rotational, linear, with and without environment usage, and even that last one I reported (which I eventually isolated as: removing a GO from an env causes all other GOs still in the env to reset their rotation).
