### ISSUE TITLE
Won't work in Unity WebGL

### ISSUE THREAD

**Issue by TestTubeGames** [Polarith/AI#24]
I've gotten the following bug using the latest version of Polarith, as well as Unity 2017.3.1p4.

Using a new project, I make a webgl build with just the 2D boids scene, all default build parameters.

It won't load in the browser, with the following error message:

Not implemented: Class::FromIl2CppType

Which repeats until the webgl crashes.

**Comment by mzettwitz** [comment]
Hi there,
We use the [IL2CPP](https://docs.unity3d.com/Manual/IL2CPP.html) backend for WebGL Support. This is a requirement for Unity to run on WebGL, as you can read [here](https://unity3d.com/de/learn/tutorials/topics/best-practices/il2cpp-mono). You need to check it during the Unity installation or install it afterwards if you use the Unity Hub.
If you are using the Pro version, note, that WebGL does NOT support threading, as you can read in a Unity [statement ](https://forum.unity.com/threads/webgl-is-threading-supported.457652/)and the IL2CPP [restrictions](https://docs.unity3d.com/Manual/ScriptingRestrictions.html). So the boids scene in the pro version won't run on WebGL, even if you've installed IL2CPP, unless you disable threading in AIMContext.

**Comment by TestTubeGames** [comment]
I do have the il2cpp backend -- and I'm able to run webgl projects.  Just not ones that have your plugin installed.  I'm curious - are you able to run a vanilla build of boids in webgl?

The threading note, while good to know, didn't affect this bug.

**Comment by mzettwitz** [comment]
I've tested both the free and pro version. The free version runs fine out of the box while I had to adjust the threading in AIMContext and disabled AIMPerformance in the pro version. Additonally I've been testing the AssetStore version against our source code version. Both run fine with default build and player settings in different browsers.
