### ISSUE TITLE
Transformation artifacts concerning static objects

### ISSUE THREAD

**Issue by ghost** [Polarith/AI#5]
Enabling our AI currently results in a bug regarding static objects. We are valiantly working on solving the issue.

![static-bug](https://cloud.githubusercontent.com/assets/23723626/20605100/e083ea52-b269-11e6-9f6f-bcd0b9d5eda9.jpg)

### Cause
It is due to the way we transform objects in order to obtain visual (mesh) oriented bounding boxes (OBBs).

### Effect
Static objects transform to other objects in the scene or disappear completely.

### Workaround
For now, there is no chance to work with static objects until the upcoming patch.

**Comment by martinkirst** [comment]
Problem is fixed in the develop branch now. So this fix will become live with the upcoming patch v1.0.1.
